### ISSUE TITLE
Some issues regarding communication with PI3hat boards

### ISSUE THREAD

**Issue by MaxKingWealth** [mjbots/pi3hat#14]
**Hi author, I am trying to use orangepi or upboard to communicate with pi3hat, after installing moteus-pi3hat, my sample code is as follows,**
import asyncio
import math
import moteus
import moteus_pi3hat
import time

async def main():
    transport = moteus_pi3hat.Pi3HatRouter(
        servo_bus_map={
            1:[11]
            },
    )
    controller = moteus.Controller(id=1, transport=transport)

**and after running it, the following error occurs， I would like to ask if there is something wrong with my operation？**

sudo python demo.py 
Traceback (most recent call last):
  File "/home/orangepi/Desktop/pi3hat/demo.py", line 96, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/orangepi/Desktop/pi3hat/demo.py", line 11, in main
    transport = moteus_pi3hat.Pi3HatRouter(
  File "/usr/local/lib/python3.10/dist-packages/moteus_pi3hat/pi3hat_router.py", line 108, in __init__
    self._impl = _pi3hat_router.Pi3HatRouter(options)
RuntimeError: Error setting realtime scheduler, try running as root (use sudo)

**Comment by jpieper** [comment]
The pi3hat is only compatible with Raspberry Pi 3 and 4, and not with the orange pi or any up boards.
