### ISSUE TITLE
no pi3hat detected

### ISSUE THREAD

**Issue by BJSingh** [mjbots/pi3hat#18]
When I tried to run sample code even as root user getting error hat not detected. But HAT (r4.4) is attached on Raspberry Pi 4 Model B Rev 1.5

root@raspberrypi:/home/pidemo/pi3hat/lib/python/examples# python3 raw_can_example.py
Traceback (most recent call last):
  File "/home/pidemo/pi3hat/lib/python/examples/raw_can_example.py", line 92, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pidemo/pi3hat/lib/python/examples/raw_can_example.py", line 39, in main
    transport = moteus_pi3hat.Pi3HatRouter(can=can_config)
  File "/usr/local/lib/python3.9/dist-packages/moteus_pi3hat/pi3hat_router.py", line 108, in __init__
    self._impl = _pi3hat_router.Pi3HatRouter(options)
RuntimeError: No pi3hat detected

**Comment by jpieper** [comment]
We resolved this in the mjbots Discord as likely being a problem with the Raspberry Pi used as a host.
